- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
  notify: Run Nginx

- name: Upload nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx