- name: Install nginx
  ansible.builtin.apt:
    name:
      - nginx
  notify: Run Nginx

- name: Upload website page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Upload nginx config
  template:
    src: default.j2
    dest: /etc/nginx/sites-enabled/default
  notify: Restart Nginx