- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Update CA certificates
  ansible.builtin.apt:
    name: ca-certificates>=20211000*

- name: Setup rsyslog
  template:
    src: 50-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
  notify:
    Restart rsyslog