- name: Install influxdb
  apt:
    deb: https://dl.influxdata.com/influxdb/releases/influxdb_1.8.10_amd64.deb
  notify: Run influxdb

- name: Start influxdb
  service:
    name: influxdb
    state: started
    enabled: yes

- name: Upload influxdb config
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
  notify: Restart influxdb