- name: Reload systemctl
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Run influxdb exporter
  service:
    name: prometheus-influxdb-exporter
    state: started
    enabled: yes

- name: Restart influxdb exporter
  service:
    name: prometheus-influxdb-exporter
    state: restarted