- name: Get grafana structure vars
  include_vars: grafana_structure.yaml

- name: Get public ips
  include_vars: ./group_vars/ips.yaml

- name: Create grafana container
  community.docker.docker_container:
    name: grafana
    image: grafana/grafana
  notify: Run grafana

- name: Create grafana directories
  file:
    path: "{{ grafana_path }}{{ item }}"
    state: directory
    recurse: yes
  loop: "{{ dirs }}"

- name: Create grafana files
  template:
    src: "{{ item.split('/')[-1] }}.j2"
    dest: "{{ grafana_path }}{{ item }}"
  loop: "{{ files }}"
  notify: Restart grafana