- name: Operations on local machine
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
    - localhost

- name: Gather facts
  hosts: remote_hosts
  become: yes
  gather_facts: yes
  tags:
    - always
    - facts

- name: Remote hosts setup
  hosts: remote_hosts
  become: yes
  gather_facts: no
  roles:
    - remote_hosts
    - node_exporter
    - backup
  tags:
    - remote_hosts

- name: DNS server
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind
  tags:
    - dns

- name: Update for dns server
  hosts: remote_hosts
  become: yes
  gather_facts: no
  roles:
    - remote_network

- name: Monitoring server
  hosts: monitoring
  become: yes
  gather_facts: no
  roles:
    - prometheus
    - grafana
    - nginx
  tags:
    - monitoring_server
    - monitoring

- name: Database server
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql
    - mysql_backup
  tags:
    - mysqlserver

- name: Web server
  hosts: web_servers
  become: yes
  gather_facts: no
  roles:
    - agama
    - uwsgi
    - nginx

- name: DB monitoring
  hosts: db_servers
  become: yes
  gather_facts: no
  roles:
    - mysql_exporter
  tags:
    - monitoring
    - sql_monitoring

- name: DNS monitoring
  hosts: dns_servers
  become: yes
  gather_facts: no
  roles:
    - bind_exporter
  tags:
    - monitoring
    - dns_monitoring

- name: Nginx monitoring
  hosts:
    - web_servers
    - monitoring
  become: yes
  gather_facts: no
  roles:
    - nginx_exporter
  tags:
    - monitoring
    - nginx_monitoring

- name: InfluxDB
  hosts:
    - influxdb
  become: yes
  gather_facts: no
  roles:
    - influxdb
    - influxdb_backup
  tags:
    - influxdb

- name: Influxdb-exporter
  hosts:
    - influxdb
  become: yes
  gather_facts: no
  roles:
    - influxdb_exporter
  tags:
    - influxdb_monitoring

- name: pinger
  hosts:
    - pinger
  become: yes
  gather_facts: no
  roles:
    - pinger
  tags:
    - pinger

- name: telegraf
  hosts:
    - influxdb
  become: yes
  gather_facts: no
  roles:
    - telegraf
  tags:
    - telegraf

- name: rsyslog logging
  hosts:
    - remote_hosts
  become: yes
  gather_facts: no
  roles:
    - rsyslog
  tags:
    - rsyslog

