- block:
  - name: Prepare vars
    template:
      src: ns_records.yaml.j2
      dest: roles/nsupdate/vars/ns_records.yaml
    delegate_to: localhost
  become: no

- name: Add new hosts
  include_vars:
    file: ns_records.yaml

- name: Install python dependencies
  apt:
    name: python3-dnspython

- name: Add dns records
  nsupdate:
    key_algorithm: hmac-sha256
    key_name: "rndc-key"
    key_secret: "{{ ns_update_key }}"
    server: localhost
    zone: "{{ startup_name }}"
    type: "{{ item.type }}"
    record: "{{ item.name }}"
    value: "{{ item.address }}"
  loop: "{{ ns_hosts }}"