{
 "title": "Main",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bind9",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WEB Server",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"binary0ne-1:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "selects/m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=\"select\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queries/m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(bind_resolver_queries_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests/m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{instance=\"binary0ne-1:9113\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU/RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "binary0ne-1 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum((avg by (instance, mode) (irate(node_cpu_seconds_total{mode!='idle', instance=\"binary0ne-1:9100\"}[30s])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "binary0ne-2 CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum((avg by (instance, mode) (irate(node_cpu_seconds_total{mode!='idle', instance=\"binary0ne-2:9100\"}[30s])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "binary0ne-1 RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "(100 * (1 - ((avg_over_time (node_memory_MemFree_bytes[30s]) + avg_over_time(node_memory_Cached_bytes[30s]) + avg_over_time(node_memory_Buffers_bytes[30s])) / avg_over_time(node_memory_MemTotal_bytes[30s]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "binary0ne-2 RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "(100 * (1 - ((avg_over_time (node_memory_MemFree_bytes[30s]) + avg_over_time(node_memory_Cached_bytes[30s]) + avg_over_time(node_memory_Buffers_bytes[30s])) / avg_over_time(node_memory_MemTotal_bytes[30s]))))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}