{
 "title": "MySQL",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "SQL id",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_server_id",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Read_only",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mysql_global_variables_read_only",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SlaveIO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SlaveSQL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Influx",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "pings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "dst" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rtt",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "log types",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "severity" ], "type": "tag" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "syslog",
     "query": "SELECT count(\"message\") FROM \"syslog\" WHERE $timeFilter GROUP BY time($__interval), \"severity\"",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    },
    {}
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "MySQL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mysql_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bind9",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "bind_up", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "WEB Server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{instance=\"binary0ne-1:9113\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "InfluxDB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_exporter_stats_query_success",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "selects/m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=\"select\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queries/m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(bind_resolver_queries_total[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "requests/m",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_http_requests_total{instance=\"binary0ne-1:9113\"}[1m])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "writes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "influxdb_write_write_ok{instance=\"binary0ne-1:9424\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "CPU/RAM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "binary0ne-1 CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum((avg by (instance, mode) (irate(node_cpu_seconds_total{mode!='idle', instance=\"binary0ne-1:9100\"}[30s])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "binary0ne-2 CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum((avg by (instance, mode) (irate(node_cpu_seconds_total{mode!='idle', instance=\"binary0ne-2:9100\"}[30s])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "binary0ne-1 RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(100 * (1 - ((avg_over_time (node_memory_MemFree_bytes[30s]) + avg_over_time(node_memory_Cached_bytes[30s]) + avg_over_time(node_memory_Buffers_bytes[30s])) / avg_over_time(node_memory_MemTotal_bytes[30s]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "binary0ne-2 RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "(100 * (1 - ((avg_over_time (node_memory_MemFree_bytes[30s]) + avg_over_time(node_memory_Cached_bytes[30s]) + avg_over_time(node_memory_Buffers_bytes[30s])) / avg_over_time(node_memory_MemTotal_bytes[30s]))))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}