- name: Add backup group
  ansible.builtin.group:
    name: backup
    state: present

- name: Add backup user
  ansible.builtin.user:
    name: backup
    group: backup
    shell: /bin/bash
    home: /home/backup
    create_home: true

- name: Ensure .ssh exists
  file:
    path: /home/backup/.ssh
    state: directory


- name: Generate keypair
  community.crypto.openssh_keypair:
    path: /home/backup/.ssh/id_rsa

- name: Change ownership
  file:
    path: /home/backup/.ssh/id_rsa
    owner: backup
    group: backup

- name: Add SSH keys for users
  ansible.posix.authorized_key:
    user: backup
    key: "{{ backup_ssh }}"

- name: Add to known hosts
  template:
    src: known_hosts.j2
    dest: ~backup/.ssh/known_hosts
    group: backup
    owner: backup

- name: Ensure restore folder is created
  file:
    path: /home/backup/restore
    state: directory
    owner: backup
    group: backup

- name: Install duplicity
  apt:
    name: duplicity