- name: Run nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes

- name: Restart nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: restarted