- name: Install mysql exporter
  ansible.builtin.apt:
    name:
      - prometheus-mysqld-exporter
  notify: Run mysql exporter

- name: Add slave status exporter
  copy:
    src: prometheus-mysqld-exporter
    dest: /etc/default/prometheus-mysqld-exporter
  notify: Restart mysql exporter

- name: Create mysql monitoring user
  community.mysql.mysql_user:
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Upload mysql exporter config
  template:
    src: .my.cnf.j2
    dest: ~prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '440'
  notify: Restart mysql exporter

- name: Wait for mysql
  ansible.builtin.pause:
    seconds: 20

- name: Start mysql exporter
  service:
    name: prometheus-mysqld-exporter
    state: started
    enabled: yes