- name: Install mysql exporter
  ansible.builtin.apt:
    name:
      - prometheus-mysqld-exporter
  notify: Run mysql exporter

- name: Create mysql monitoring user
  community.mysql.mysql_user:
    login_user: root
    name: "{{ mysql_exporter_user }}"
    password: "{{ mysql_exporter_password }}"
    priv: "*.*:PROCESS, REPLICATION CLIENT, SELECT"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Upload mysql exporter config
  template:
    src: .my.cnf.j2
    dest: ~prometheus/.my.cnf
    owner: prometheus
    group: prometheus
    mode: '440'
  notify: Restart mysql exporter