- name: Run keepalived
  service:
    name: keepalived
    state: started
    enabled: yes

- name: Restart keepalived
  service:
    name: keepalived
    state: restarted
    enabled: yes

- name: Reload systemctl
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Run keepalived exporter
  service:
    name: prometheus-keepalived-exporter
    state: restarted
    enabled: yes