- name: Install MySQL
  ansible.builtin.apt:
    name:
      - mysql-server
  notify: Run MySQL-server

- name: Upload MySQL config
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: Restart MySQL-server

- name: Install dependencies for ansible
  ansible.builtin.apt:
    name:
      - python3-pymysql

- name: MySQL database
  community.mysql.mysql_db:
    name: '{{ mysql_database }}'
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: agama MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    host: "%"
    priv: "{{ mysql_database }}.*:ALL"
    login_unix_socket: /var/run/mysqld/mysqld.sock