- name: Install bind exporter
  ansible.builtin.apt:
    name:
      - prometheus-bind-exporter
  notify: Run bind exporter

- name: Run bind exporter
  service:
    name: prometheus-bind-exporter
    state: started
    enabled: yes