- name: Install nginx exporter
  ansible.builtin.apt:
    name:
      - prometheus-nginx-exporter
  notify:
  - Run nginx exporter
  - Restart Nginx

- name: Run nginx exporter
  service:
    name: prometheus-nginx-exporter
    state: started
    enabled: yes