- name: Run grafana
  docker_container:
    name: grafana
    state: started
    exposed_ports: "{{ grafana_port }}"
    published_ports: "{{ grafana_port }}:3000"

- name: Restart grafana
  docker_container:
    name: grafana
    state: started
    restart: yes
    exposed_ports: "{{ grafana_port }}"
    published_ports: "{{ grafana_port }}:3000"
    volumes: "{{ grafana_path }}:/etc/grafana"