- name: Run MySQL-server
  service:
    name: mysql
    state: started
    enabled: yes

- name: Restart MySQL-server
  service:
    name: mysql
    state: restarted

- name: Reset MySQL source
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  loop:
    - stopreplica
    - resetprimary
  when: inventory_hostname in groups['db_master']

- name: Reset MySQL replica
  community.mysql.mysql_replication:
    mode: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    primary_host: "{{ groups['db_master'][0] }}"
    primary_user: "{{ replication_user }}"
    primary_password: "{{ replication_password }}"
  loop:
    - stopreplica
    - changeprimary
    - resetreplica
    - startreplica
  when: inventory_hostname in groups['db_slave']