- name: Install bind
  ansible.builtin.apt:
    name:
      - bind9
  notify: Start bind

- name: Update bind config
  template:
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
  notify: Restart bind
