- name: Add telegraf key
  ansible.builtin.apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add telegraf repo
  apt_repository:
    repo: deb https://repos.influxdata.com/debian stable main
    state: present

- name: Install telegraf
  apt:
      name: telegraf
      state: present
      update_cache: yes
  notify: Run telegraf

- name: Upload telegraf config
  copy:
    src: telegraf.conf
    dest: /etc/telegraf/telegraf.conf
  notify: Restart telegraf

- name: Run telegraf
  service:
    name: telegraf
    state: started
    enabled: yes
